apiVersion: v1
kind: Service
metadata:
  name: nginx-prod
  namespace: nginx-cicd-argo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
  selector:
    app: nginx-prod
