apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev
  namespace: nginx-cicd-github
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dev
  template:
    metadata:
      labels:
        app: nginx-dev
    spec:
      containers:
      - name: nginx
        image: osoriano/nginx-cicd:main
        ports:
        - name: traffic-port
          containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /
